# Generated by Django 4.0.2 on 2022-12-02 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('land', '0002_room_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='abc', max_length=50)),
                ('number', models.CharField(default='abc', max_length=15)),
                ('country', models.CharField(default='abc', max_length=20)),
                ('desc', models.TextField()),
                ('room', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='land.room')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
