# Generated by Django 4.0.2 on 2022-12-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='book',
            name='desc',
        ),
        migrations.AddField(
            model_name='book',
            name='fname',
            field=models.CharField(default='abc', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='lname',
            field=models.CharField(default='abc', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='noa',
            field=models.CharField(default='abc', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='noc',
            field=models.CharField(default='abc', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='pob',
            field=models.CharField(default='abc', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='sr',
            field=models.CharField(default='abc', max_length=50),
        ),
    ]
