# Generated by Django 4.0.2 on 2022-12-05 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_name_book_email_remove_book_desc_book_fname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
