# Generated by Django 4.0.2 on 2022-12-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='booking_username',
            field=models.CharField(default='jagan', max_length=30),
        ),
    ]
