# Generated by Django 4.0.2 on 2022-12-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_book_booking_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='confirm',
            field=models.CharField(default='Not Confirmed', max_length=10),
        ),
    ]
