# Generated by Django 4.0.2 on 2022-12-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_book_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='country',
            field=models.IntegerField(default='1234567890'),
        ),
    ]
