# Generated by Django 4.0.2 on 2022-12-12 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_book_country_alter_book_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='confirm',
        ),
    ]
