# Generated by Django 4.0.2 on 2022-11-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rent',
            field=models.CharField(default='á', max_length=50),
        ),
    ]
