# Generated by Django 4.0.2 on 2022-12-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_room_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='desc',
            field=models.TextField(default='abc'),
        ),
    ]
