# Generated by Django 4.0.2 on 2022-12-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0003_room_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(upload_to='room'),
        ),
    ]
