# Generated by Django 4.0.2 on 2022-12-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0004_alter_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='street',
            field=models.CharField(default='abc', max_length=50),
        ),
    ]
