# Generated by Django 4.0.2 on 2022-12-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0005_room_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='rent',
            field=models.FloatField(),
        ),
    ]
