# Generated by Django 4.0.2 on 2022-12-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0006_alter_room_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='lat',
            field=models.FloatField(default=3.1256),
        ),
        migrations.AddField(
            model_name='room',
            name='long',
            field=models.FloatField(default=3.1256),
        ),
    ]
