# Generated by Django 4.0.2 on 2022-12-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0007_room_lat_room_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='room',
            name='long',
        ),
        migrations.AddField(
            model_name='room',
            name='eircode',
            field=models.CharField(default='D02 R590', max_length=20),
        ),
    ]
